### ISSUE TITLE
Enabling fsoi sets of a form other than (1, ... n)

### ISSUE THREAD

**Issue by gcskoenig** [gcskoenig/rfi#30]
This probably mainly concerns the explainer class.

Especially problematic: fsoi being used as indices in a result matrix. Made to break.

**Comment by Valentyn1997** [comment]
I actually also had many problems with this indexing. I suppose we can shift to DataFrames, so that features will indexed by column names

**Comment by gcskoenig** [comment]
Yes, I guess that would be a good idea. It would be quite a refactoring though :) I will look into it asap.

**Comment by gcskoenig** [comment]
- [ ] explainer
  - [x] Init:
    * the training data
  - [x] rfi
    * Perturbed_foss = np.zeros((nr_fsoi, nr_runs, nr_obs)) -> multiindex obs_nr, run_nr
    * lss = np.zeros((nr_fsoi, nr_runs, X_test.shape[0])) -> multiindex as above
    * X_test_one_perturbed (nr_obs, nr_features) -> normal structure
    * X_test_model (nr_obs, nr_features) -> normal structure
  - [ ] rfa
    * Perturbed_reconstr = (nr_fsoi, nr_obs, nr_runs, nr_features)
    * perturbed_baseline = (nr_obs, nr_runs, nr_features)
    * sample_decorr
    * lss = np.zeros((nr_fsoi, nr_runs, X_test.shape[0]))
    * X_test_reconstructed = np.array(perturbed_baseline[:, kk, :])
  - [ ] decomposition
    * values = np.zeros((len(fsoi), nr_components, nr_orderings, nr_runs))
    * rfs = rfs = np.zeros (nr_runs, len(utils.flatten(partial_ordering)) + 1, len(fsoi)))
  - [ ] sage
    * lss = (len(self.fsoi), nr_runs, X_test.shape[0], nr_orderings))
    * fix ordering!
    * X_test_perturbed = (nr obs_ nr cols)
    * 
  - [ ] fa: will be deprecated. moved to end of file.
- [x] sampler
  - [ ] Gaussian
  - [ ] CNF
  - [ ] MDN
- [ ] decorrelator (party adjusted, now unstable)
- [ ] backend (would need readjustment of sampler class)
- [x] explanation
- [ ] Decompositionexplanation
